apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jmdhxmwq2-nodejs 
  janus-idp.io/tekton: jmdhxmwq2-nodejs
  backstage.io/kubernetes-id: jmdhxmwq2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jmdhxmwq2-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml